<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.u3l54oY' shared service.

return $this->privates['.service_locator.u3l54oY'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('film' => function (): \App\Entity\Film {
    return ($this->privates['.errored..service_locator.u3l54oY.App\Entity\Film'] ?? $this->load('getFilmService.php'));
}));
