<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xkmHvPK' shared service.

return $this->privates['.service_locator.xkmHvPK'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('acteur' => function (): \App\Entity\Acteur {
    return ($this->privates['.errored..service_locator.xkmHvPK.App\Entity\Acteur'] ?? $this->load('getActeurService.php'));
}));
