<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IZGImX4' shared service.

return $this->privates['.service_locator.IZGImX4'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('genre' => function (): \App\Entity\Genre {
    return ($this->privates['.errored..service_locator.IZGImX4.App\Entity\Genre'] ?? $this->load('getGenreService.php'));
}));
