<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.xkmHvPK.App\Entity\Acteur' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.xkmHvPK": it references class "App\\Entity\\Acteur" but no such service exists.');
