<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.IZGImX4.App\Entity\Genre' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.IZGImX4": it references class "App\\Entity\\Genre" but no such service exists.');
