<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WehOvbw' shared service.

return $this->privates['.service_locator.WehOvbw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('realisateur' => function (): \App\Entity\Realisateur {
    return ($this->privates['.errored..service_locator.WehOvbw.App\Entity\Realisateur'] ?? $this->load('getRealisateurService.php'));
}));
