<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTA143WQ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTA143WQ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTA143WQ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTA143WQ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTA143WQ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TA143WQ',
    'container.build_id' => '6dbdda5e',
    'container.build_time' => 1534238196,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTA143WQ');
